---
title: "GeneFunnel Benchmarks Viewer"
output:
  flexdashboard::flex_dashboard:
    source_code: embed
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include = FALSE}
#    This file is part of genefunnel-benchmarks.
#    Copyright (C) 2024  Emir Turkes, UK DRI at UCL
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Emir Turkes can be contacted at emir.turkes@eturkes.com

library(conflicted)
packages <- c(
  "shinyMatrix", "ComplexHeatmap", "circlize"
)
lapply(packages, FUN = library, character.only = TRUE)

top_anno <- HeatmapAnnotation(
  sample = anno_block(
    gp = gpar(fill = "lightgray", col = "lightgray"),
    labels = c("Sample 1", "Sample 2", "Sample 3", "Sample 4"),
    labels_gp = gpar(col = "black", fontsize = 15),
    height = unit(10, "mm")
  )
)

ht_opt$DIMNAME_PADDING = unit(3, units = "mm")
```

```{r}
vec <- c(
  rep(50, times = 10), rep(c(95, 5), times = 5),
  rep(5, times = 10), rep(95, times = 10)
)
set.seed(1)
noise <- round(runif(20, min = -4, max = 4))

default_mat <- matrix(
  vec + noise,
  nrow =  10,
  ncol = 4,
  dimnames = list(
    paste("Gene", toupper(letters[1:10])),
    c("Sample 1", "Sample 2", "Sample 3", "Sample 4")
  )
)

shinyApp(
  ui = fluidPage(
    sidebarPanel(
      width = 3,
      tags$h3(
        HTML("тож Click Cells to Edit Matrix тоз"), style = "text-align:center"
      ),
      matrixInput(
        "mat",
        label = "Hypothetical Raw Gene Count X Sample Matrix",
        value = default_mat
      )
    ),
    mainPanel(
      width = 4,
      plotOutput("gene_heatmap", height = "450px")
    ),
    mainPanel(
      width = 5,
      plotOutput("gse_heatmap", height = "450px")
    )
  ),
  server = function(input, output, session) {

    output$gene_heatmap <- renderPlot({
      heatmap_mat <- apply(input$mat, MARGIN = 2, FUN = as.numeric)
      rownames(heatmap_mat) <- rownames(input$mat)

      col_range <- c(
        min(heatmap_mat),
        (min(heatmap_mat) + max(heatmap_mat)) / 2,
        max(heatmap_mat)
      )

      draw(
        Heatmap(
          heatmap_mat,
          name = "Gene Expression",
          col = colorRamp2(col_range, colors = c("blue", "white", "red")),
          cluster_rows = FALSE,
          cluster_columns = FALSE,
          show_column_names = FALSE,
          top_annotation = top_anno,
          column_split = seq(4),
          column_title = "Hypothetical Raw Gene Count by Sample Matrix",
          rect_gp = gpar(col = "black", lwd = 0.5),
          column_gap = unit(1, units = "mm"),
          row_names_gp = gpar(fontsize = 15),
          column_title_gp = gpar(fontsize = 18),
          row_names_side = "left",
          heatmap_legend_param = list(
            labels_gp = gpar(fontsize = 14), title_gp = gpar(fontsize = 15),
            border = "lightgrey", title_position = "topcenter",
            grid_height = unit(4, "mm"), direction = "horizontal"
          )
        ),
        heatmap_legend_side = "top"
      )
    })

    output$gse_heatmap <- renderPlot({
      numeric_mat <- apply(input$mat, MARGIN = 2, FUN = as.numeric)
      heatmap_mat <- matrix(
        c(
          sum(numeric_mat[ , 1]) * 2 -
            sum(abs(numeric_mat[ , 1] - mean(numeric_mat[ , 1]))),
          sum(numeric_mat[ , 2]) * 2 -
            sum(abs(numeric_mat[ , 2] - mean(numeric_mat[ , 2]))),
          sum(numeric_mat[ , 3]) * 2 -
            sum(abs(numeric_mat[ , 3] - mean(numeric_mat[ , 3]))),
          sum(numeric_mat[ , 4]) * 2 -
            sum(abs(numeric_mat[ , 4] - mean(numeric_mat[ , 4])))
        ),
        nrow =  1,
        ncol = 4,
        dimnames = list("Gene Set X  \n(Genes A to J)")
      )

      bottom_anno <- HeatmapAnnotation(
        text = anno_text(
          c(
            paste0(
              "\n\n\n\nSum = ", sum(numeric_mat[ , 1]) * 2,
              "\nMean = ", mean(numeric_mat[ , 1]),
              "\nVar = ", sum(abs(numeric_mat[ , 1] - mean(numeric_mat[ , 1]))),
              "\nScore = ", sum(numeric_mat[ , 1]) * 2 -
                sum(abs(numeric_mat[ , 1] - mean(numeric_mat[ , 1])))
            ),
            paste0(
              "\n\n\n\nSum = ", sum(numeric_mat[ , 2]) * 2,
              "\nMean = ", mean(numeric_mat[ , 2]),
              "\nVar = ", sum(abs(numeric_mat[ , 2] - mean(numeric_mat[ , 2]))),
              "\nScore = ", sum(numeric_mat[ , 2]) * 2 -
                sum(abs(numeric_mat[ , 2] - mean(numeric_mat[ , 2])))
            ),
            paste0(
              "\n\n\n\nSum = ", sum(numeric_mat[ , 3]) * 2,
              "\nMean = ", mean(numeric_mat[ , 3]),
              "\nVar = ", sum(abs(numeric_mat[ , 3] - mean(numeric_mat[ , 3]))),
              "\nScore = ", sum(numeric_mat[ , 3]) * 2 -
                sum(abs(numeric_mat[ , 3] - mean(numeric_mat[ , 3])))
            ),
            paste0(
              "\n\n\n\nSum = ", sum(numeric_mat[ , 4]) * 2,
              "\nMean = ", mean(numeric_mat[ , 4]),
              "\nVar = ", sum(abs(numeric_mat[ , 4] - mean(numeric_mat[ , 4]))),
              "\nScore = ", sum(numeric_mat[ , 4]) * 2 -
                sum(abs(numeric_mat[ , 4] - mean(numeric_mat[ , 4])))
            )
          ),
          rot = 0,
          gp = gpar(fontsize = 18),
          just = "centre"
        )
      )

      col_range <- c(
        min(heatmap_mat),
        (min(heatmap_mat) + max(heatmap_mat)) / 2,
        max(heatmap_mat)
      )

      draw(
        Heatmap(
          heatmap_mat,
          name = "Gene Set Score",
          col = colorRamp2(col_range, colors = c("blue", "white", "red")),
          cluster_rows = FALSE,
          cluster_columns = FALSE,
          show_column_names = FALSE,
          top_annotation = top_anno,
          bottom_annotation = bottom_anno,
          column_split = seq(4),
          column_title = "Resulting Gene Set Enrichment by Sample Matrix",
          rect_gp = gpar(col = "black", lwd = 0.5),
          column_gap = unit(1, units = "mm"),
          row_names_gp = gpar(fontsize = 16),
          column_title_gp = gpar(fontsize = 18),
          row_names_side = "left",
          height = unit(0.5, "npc"),
          heatmap_legend_param = list(
            labels_gp = gpar(fontsize = 14), title_gp = gpar(fontsize = 15),
            border = "lightgrey", title_position = "topcenter",
            grid_height = unit(4, "mm"), direction = "horizontal"
          )
        ),
        heatmap_legend_side = "top",
        padding = unit(c(90, 2, 2, 2), units = "mm")
      )
    })

  }
)
```
